# Generated by Django 2.2.16 on 2020-10-20 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto6', '0002_insumos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumos',
            old_name='desccripsion',
            new_name='descripsion',
        ),
    ]
